// Code generated by protoc-gen-go.
// source: ball.proto
// DO NOT EDIT!

/*
Package messages is a generated protocol buffer package.

It is generated from these files:
	ball.proto
	client_request_create_world.proto
	client_request_monitor.proto
	client_request_pong.proto
	client_request.proto
	server_request_ping.proto
	server_request.proto
	server_request_register.proto

It has these top-level messages:
	Ball
*/
package messages

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type Ball struct {
	X                *int32 `protobuf:"varint,1,req,name=x" json:"x,omitempty"`
	Y                *int32 `protobuf:"varint,2,req,name=y" json:"y,omitempty"`
	DirX             *int32 `protobuf:"varint,3,req,name=dirX" json:"dirX,omitempty"`
	DirY             *int32 `protobuf:"varint,4,req,name=dirY" json:"dirY,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Ball) Reset()         { *m = Ball{} }
func (m *Ball) String() string { return proto.CompactTextString(m) }
func (*Ball) ProtoMessage()    {}

func (m *Ball) GetX() int32 {
	if m != nil && m.X != nil {
		return *m.X
	}
	return 0
}

func (m *Ball) GetY() int32 {
	if m != nil && m.Y != nil {
		return *m.Y
	}
	return 0
}

func (m *Ball) GetDirX() int32 {
	if m != nil && m.DirX != nil {
		return *m.DirX
	}
	return 0
}

func (m *Ball) GetDirY() int32 {
	if m != nil && m.DirY != nil {
		return *m.DirY
	}
	return 0
}

func init() {
}
