// Code generated by protoc-gen-go.
// source: client_request_create_world.proto
// DO NOT EDIT!

package messages

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type ClientRequestCreateWorld struct {
	Width            *int32 `protobuf:"varint,1,req,name=width" json:"width,omitempty"`
	Height           *int32 `protobuf:"varint,2,req,name=height" json:"height,omitempty"`
	Ball             *Ball  `protobuf:"bytes,3,req,name=ball" json:"ball,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *ClientRequestCreateWorld) Reset()         { *m = ClientRequestCreateWorld{} }
func (m *ClientRequestCreateWorld) String() string { return proto.CompactTextString(m) }
func (*ClientRequestCreateWorld) ProtoMessage()    {}

func (m *ClientRequestCreateWorld) GetWidth() int32 {
	if m != nil && m.Width != nil {
		return *m.Width
	}
	return 0
}

func (m *ClientRequestCreateWorld) GetHeight() int32 {
	if m != nil && m.Height != nil {
		return *m.Height
	}
	return 0
}

func (m *ClientRequestCreateWorld) GetBall() *Ball {
	if m != nil {
		return m.Ball
	}
	return nil
}

func init() {
}
