// Code generated by protoc-gen-go.
// source: client_request_monitor.proto
// DO NOT EDIT!

package messages

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type ClientRequestMonitor struct {
	X                *int32 `protobuf:"varint,1,req,name=x" json:"x,omitempty"`
	Y                *int32 `protobuf:"varint,2,req,name=y" json:"y,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *ClientRequestMonitor) Reset()         { *m = ClientRequestMonitor{} }
func (m *ClientRequestMonitor) String() string { return proto.CompactTextString(m) }
func (*ClientRequestMonitor) ProtoMessage()    {}

func (m *ClientRequestMonitor) GetX() int32 {
	if m != nil && m.X != nil {
		return *m.X
	}
	return 0
}

func (m *ClientRequestMonitor) GetY() int32 {
	if m != nil && m.Y != nil {
		return *m.Y
	}
	return 0
}

func init() {
}
