// Code generated by protoc-gen-go.
// source: server_request_register.proto
// DO NOT EDIT!

package messages

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type ServerRequestRegister struct {
	W                *int32 `protobuf:"varint,1,req,name=w" json:"w,omitempty"`
	H                *int32 `protobuf:"varint,2,req,name=h" json:"h,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *ServerRequestRegister) Reset()         { *m = ServerRequestRegister{} }
func (m *ServerRequestRegister) String() string { return proto.CompactTextString(m) }
func (*ServerRequestRegister) ProtoMessage()    {}

func (m *ServerRequestRegister) GetW() int32 {
	if m != nil && m.W != nil {
		return *m.W
	}
	return 0
}

func (m *ServerRequestRegister) GetH() int32 {
	if m != nil && m.H != nil {
		return *m.H
	}
	return 0
}

func init() {
}
